### Posts API Tests

### 1. Create a new post
POST http://localhost:3000/post
Content-Type: application/json

{
  "title": "My First Post",
  "content": "This is the content of my first post",
  "sender": "user123"
}

###

### 2. Create another post
POST http://localhost:3000/post
Content-Type: application/json

{
  "title": "Second Post",
  "content": "This is another post with different content",
  "sender": "user456"
}

###

### 3. Create post with missing field (should fail)
POST http://localhost:3000/post
Content-Type: application/json

{
  "title": "Incomplete Post",
  "content": "This post is missing the sender field"
}

###
